simulation:
  backend: pybullet  # pybullet | robosuite | gym
  timestep: 0.0041666667
  gravity: -9.81
  gui: true
  max_steps_per_episode: 300
  robot_urdf: kuka_iiwa/model.urdf
  base_position: [0.0, 0.0, 0.0]
  base_orientation_euler: [0.0, 0.0, 0.0]
  enable_camera: false
  camera_position: [0.0, 0.0, 0.0]
  camera_orientation_euler: [0.0, 0.0, 0.0]


gym:
  entry_point: gymnasium.make
  env_kwargs:
    id: Pendulum-v1
    render_mode: human
  obs_key: null

model:
  architecture: mlp
  input_dim: 32
  action_dim: 7
  hidden_sizes: [256, 256]
  learning_rate: 0.0003
  weight_decay: 0.0
  gamma: 0.99
  seed: 42
  prompt_conditioning: true
  prompt_embed_dim: 128
  use_diffusion_policy: false
  dp_ctor_path: ""
  dp_ctor_kwargs: {}

gepa:
  llm_provider: mock
  population_size: 8
  pareto_front_k: 4
  mutation_rate: 0.3
  reflection_weight: 0.5
  evaluation_episodes: 1
  max_iterations: 5
  base_prompt: "Control the robot arm to reach the target smoothly."

experiment:
  project_name: gepa_behavior
  log_dir: ./runs
  checkpoint_dir: ./checkpoints
  seed: 42
  episodes: 3
  steps_per_episode: 200

world_model:
  enabled: true
  hidden_dim: 256
  learning_rate: 0.001
  weight_decay: 0.0
  rollout_horizon: 3
  train_steps_per_episode: 100
  batch_size: 256

## Examples only (commented out); uncomment to try Gymnasium instead
# gym:
#   entry_point: gymnasium.make
#   env_kwargs:
#     id: Pendulum-v1
#   obs_key: null
